### ISSUE TITLE
关于内置播放器

### ISSUE THREAD

**Issue by Tardis07** [mastermay/quench#10]
虽然主题内置了短标签xiami，但是感觉这个功能太鸡肋而显得有些累赘，原因如下：

- 支持的平台少，只有xiami而没有网易云音乐或者其他音乐平台
- 分析错误，会把所属专辑名分析成歌曲名，暂未找到相关代码
- 对https的支持差，开启全站https后需手动修改jquery-jplayer.min.js line:100
- 不支持音乐list（至少我没看出怎么用0.0）

不过总的来说，免费的主题提供这样的外链音乐短标签也是很良心的，点个赞，这个主题如果有意继续改进的话，不知能否合作开发

**Comment by Tardis07** [comment]
关于分析错误这个，找到了，原因是xiami的api提供的title就是专辑名称，这是硬伤233333

**Comment by mastermay** [comment]
1. API 接口错误已修复，详见 https://lophita.com/xiami-music-api.html，并且支持网易云音乐。但目前主题并不支持网易云音乐
2. API 支持 **https**，*主题已更新*
3. 暂不支持专辑 / 歌单
4. 主题目前仍在维护中，修复 BUG 或添加新功能可直接提交 PR
