### ISSUE TITLE
希望加入有人回复评论自动发送邮件提醒对方功能

### ISSUE THREAD

**Issue by YangXuran** [mastermay/quench#5]
这样就不需要每次更新都要改了，还有能留个捐赠渠道吗

**Comment by mastermay** [comment]
默认是支持评论邮件通知的，详见[此处](https://github.com/mastermay/quench/blob/master/functions/comments.php#L233)。
捐赠就不需要啦:)

**Comment by YangXuran** [comment]
噗，目测是我用PHP邮件服务器然后被Gmail扔了
